AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Streamdata.io Github Events Streaming to Amazon S3 Data Lake Using Lambda.
Resources:
  streamdataiogithubevents:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: s3://streamdata-serverless/streamdata-io-github-events/package.zip
      Description: Streamdata.io Github Events Streaming to Amazon S3 Data Lake Using Lambda.
      MemorySize: 128
      Timeout: 300
      Policies:
        - LambdaInvokePolicy:
            FunctionName: streamdata-io-github-events
        - S3CrudPolicy:
            BucketName: streaming-data-lake
      Environment:
        Variables:
          targetUrl: 'https://api.github.com/events'
          s3bucket: streaming-data-lake
          targetFolder: github-events
          appToken: Streamdata.io-Application-Token
          github_token: Github-Token
